[EOSIO Dawn 3.0]

== Executive summary
This is a deep dive into EOSIO Dawn 3.0. The information in this document is derived from the EOSIO MIT Licensed GitHub documentation and code. The ideas and conclusions in this document are based on the actual results of first hand implementation and testing of the EOSIO software. Real examples are provided, and as such, the verbose content can be found in the appendicies.

== Overview

=== Codebase
EOS expect that C++ will be the best language for developing high-performance and secure smart contracts and therefore EOS plan to use C++ for the foreseeable future [1]

=== Smart Contracts
EOS smart contracts have 2 communication modes; inline and deferred, these can both be defined within a given smart contract

Inline:: 
Guaranteed to execute in the current transaction, or unwind
Scope and authority is explicitly aligned with the original contract
No notification of completion
Nothing is scheduled for future, beyond the current transaction

Deferred::
Execution set for a time in the future, at a producer’s discretion, but can timeout
Able to reach out to different scopes as well as carry the authority of the contract that sends them
Able to communicate the result of the completed communication
Can be considered scheduled in nature, for future transactions


=== Accounts




== References
////
Source: https://github.com/EOSIO/eos/wiki/Smart-Contract
License: The MIT License (MIT)
Added by: @tpmccallum
////
[1] https://github.com/EOSIO/eos/wiki/Smart-Contract

== Appendices

=== Appendix A

