[A Tour of EOS]

:revnumber: v1.0
:revdate: 2018-05-19 (yyyy-mm-dd)
:revremark: This document is a written as an informative chapter, it is a tour of EOS

= EOS

== What is EOS
EOS is a very interesting blockchain implementation. Unlike other blockchain implementations, the creators of the EOS blockchain software, https://block.one/[block.one], are not actually implementing the EOS blockchain software. They are just releasing the open source code, which anyone in the world can implement themselves.

== The EOS Initial Coin Offering (ICO)
The EOS ICO is the longest running ICO in blockchain history. The EOS ICO, is being run on the Ethereum network over a 350 day period (July 2017 to July 2018). During each new day, two million EOS tokens are made available to buyers over a 23 hour purchasing period. The EOS tokens are purchased directly on the Ethereum network using the Ethereum cryptocurrency, known as ETH. 

The allocation of the total 1 000, 000, 000 (one billion) EOS token supply, is as follows 

100, 000, 000:: One hundred million EOS tokens are reserved for the creators of the EOS software (block.one). These one hundred million tokens can not be traded or transferred on the Ethereum network

700, 000, 000:: Seven hundred million EOS tokens are being split evenly into the 350 consecutive 23 hour purchasing periods 

200, 000, 000:: Initially, two hundred million EOS tokens were distributed during a 5 day period beginning on June 26 2017 and ending on July 1 2017.

== The EOS launch
As mentioned previously, block.one, the creators of EOS are not implementing their EOS blockchain software. Instead they are releasing the software which anyone can implement. The software launch, originally scheduled for June 2nd 2018, will open the flood gates for users from around the globe to download, configure and deploy the production ready blockchain software. 

== The EOS tokens
At the time of launch, the 1 billion EOS tokens residing on the Ethereum network will be frozen. The execution of this snapshot will completely prevent users from transferring tokens on the Ethereum network. After the snapshot, the entire record of EOS's Ethereum ERC20 token ownership will be migrated to an EOS compatible snapshot. This EOS snapshot will be part of the genesis state for any and all future EOS blockchain implementations. What this means is that every EOS blockchain implementation, deployed after the EOS software launch date will carry the full 1 billion tokens.

== Registering EOS tokens
By default, the Ethereum blockchain has no way of figuring out which EOS users (those who have EOS private keys) own EOS tokens. At the simplest level, the Ethereum blockchain only knows which of its Ethereum users purchased EOS tokens during the ICO. This information is not transferrable or useful to the EOS blockchain in its native state. EOS tokens, which were purchased on the Ethereum network as part of the EOS ICO, will only exist after the snapshot if they are registered to an EOS private key. This registration process must be performed by the person who purchased EOS tokens in the ICO and this registration must be performed before the snapshot/freeze. The registration process is performed by running the "register" function which resides inside EOS's Ethereum ERC20 token contract.

== Any questions so far?
You may be wondering quite a bit by now. For example, if anyone can deploy the EOS software won't there be more than one chain? Who is going to mine all of these blockchains? How can a cryptocurrency exchange cope with trading EOS tokens given that the company block.one, who created the ICO, is not implementing a blockchain?

You may be asking deeper questions such as the following. What if nobody in the community implements EOS at all? What happens if a user does not register their EOS tokens before the snapshot? What if 2 or more competing software developers each deploy an outstanding EOS blockchain implementation? Can there actually be more than one EOS blockchain implementation? If so, how will the cryptocurrency exchanges maintain liquidity in the event that there are multiple EOS blockchains which all carry the snapshot of EOS tokens onboard. 

== Some answers to these questions
Firstly, as mentioned above EOS is quite unique from most of the other blockchain implementations, which are currently in production. For example, unlike Bitcoin and Ethereum which use the Proof of Work (PoW) consensus algorithm, EOS uses its own Delegated Proof of Stake (DPoS) consensus algorithm. We will cover this in detail soon, but for now let's answer a few more broad questions to set the stage.

=== There will be only one EOS blockchain
Only one of the EOS blockchain implementations, deployed by the global community, will become EOS. The theory behind the community driven nature of EOS is that the world's most talented software developers will organically gravitate towards the best EOS blockchain implementation. That is, developers will want to be a part of the blockchain implementation with the most chance of success and will therefore converge.

=== How does an EOS blockchain implementation qualify to be "the one"
Launching an EOS blockchain implementation is only half the battle. In order for a single EOS blockchain implementation to even be a valid contender, 15% of all EOS token holders (within the global community) have to cast their vote together on that single chain. In addition to this, the implementor of the EOS blockchain software must create a constitution which will replace the default constitution. If neither of the above points are achieved the blockchain implementation will not be valid. We will discuss the constitution and governence in detail soon.

=== Some statistics on EOS token registration
Only 34.3% of EOS tokens have actually been registered (as at 19th May 2018). This statistic, gathered less than two weeks before the EOS software launch, could be an indication that token holders from around the globe may struggle to reach the 15% voting threshold on a single EOS blockchain implementation. This would especially be the case if there were many EOS blockchain implementations to choose from, and say perhaps users were loyal to EOS implementations in or around their geographical location etc. The rate of EOS token registration does not seem high, given that around 13% of EOS tokens were registered an or around 1st April 2018. That is only a registration rate of around 20% per month, with less than two weeks remaining.

An EOS token holder may experience delays when calling EOS's Ethereum ERC20 "register" function on the Ethereum network. https://etherscan.io/txsPending?a=0xd0a6E6C54DbC68Db5db3A091B171A77407Ff7ccf[Etherscan] shows between 500 and 700 pending EOS transactions at any given time. The congestion, for the register transaction, on the Ethereum network may be due, in part, to the fact that the register function is of little use to Ethereum's PoW mining community. The register function sends 0 ETH yet provides a naturally fair and conservitive amount of gas rewards, by default, to the miners. These pending transactions, experienced with other ERC20 tokens as well, may increase as more and more users attempt to register at the last minute. 

=== EOS and cryptocurrency exchanges
https://youtu.be/2A0dLVBlfcU?t=25[EOSGo] recently reported that the cryptocurrency exchange Bitfinex will support EOS airdrops and voting. https://github.com/bitfinexcom/bip/blob/master/proposals/001.md[A draft proposal] of the Bitfinex open-source voting tool and https://www.reddit.com/r/eos/comments/8ifztx/bitfinex_ama_eos_may_10th/dyrmvnn/[an online statement] (by the moderator of r/bitfinex and r/ethfinex) reveals that the aim of the voting tool is to ensure integrity and verifiability with regards to the origin of funds used for the EOS Block Producer vote - "Bitfinex users will be free to vote for block producers as they wish, in a verifiably transparent manner."

DPoS

Governance

The Constitution

Arbitration


Block producer candidate voting portal
