[Bancor]
Disclaimer: This is my brief summary of Bancor. This information is based on my personal understanding of the white paper, the web site and the openly licensed Solidity smart contract code which resides in GitHub. This document offers no advice nor opinions. This document has only been produced to exercise my personal understanding; it serves as a place to jot down my notes to prompt my thinking. 

= Bancor

== Background

Bancor is essentially a non-profit automated market maker. The governing software will sell tokens to buyers and buy tokens from sellers. This trading activity has no spread (profits taken by the traditional synchronous buy/sell process). 

=== Traditional synchronous trading

By synchronous, we mean that at any given time (in the context of a trade) we have a double coincidence of wants. Put simply, in traditional trading, the system has to find two parties who agree to buy/sell each other's tokens, at a particular price, at that particular point in time (the synchronous trade). 

=== Asynchronous trading 

Bancor is different to traditional markets (which facilitate synchronous trades). Bancor provides constant liquidity. The system will always trade tokens because tokens are mathematically linked to each other. Anytime a buyer or seller takes action the asynchronous nature of the system will respond appropriately with a trade. "The Bancor protocol represents the first technological solution for the classic problem in economics known as the “Double Coincidence of Wants”, in the domain of asset exchange" [1].

=== Liquidity vs price

It is important to discern liquidity from price. Liquidity is the ability to perform a trade; Bancor always provides liquidity regardless of price. Price can change due to several factors. For example, if the holder of a token believes that there is no utility or purpose for the token they may sell the token. If this continues (holders not seeing utility or purpose and therefore selling tokens) the price will become lower and lower. Interestingly, if others do see potential and purpose of a token they will buy-in at a certain price point. The buying of these same tokens will then increase the tokens price. This supply and demand tug-of-war is fundamentally known as price discovery.

=== Arbritrage

Bancor is interesting in that it provides its own online exchange between the world's supply of tokens and in addition provides the open source source code (used by its own exchange) to implement this sort of exchange on other blockchain networks. 

In a single exchange situation (where a given token is only listed on one exchange interface) price discovery works as previously described. When tokens are selling the price decreases, when tokens are being bought the price increases. Of course buyers and sellers constantly make decisions and take action to buy and sell their tokens at certain price points. Again, this supply and demand is basic price discovery.

When a given token is listed on many exchanges, we have this notion of arbritrage. Arbritrage essentially involves the buying and selling of tokens via exchanges which are not synced. This buying and selling (buying at a low price on one exchange and instantly selling for a higher price on another exchange) for profit is essentially a way in which a trader can take advantage of pricing indiscrepancies (pricing errors) of the same commodity which is listed on different exchanges.

Bancor provides constant liquidity and so it can be surmised that its more efficient market making should result in smoother and shorter deviations from a particular tokens overall fair value price point.

== Bancor technology

Bancor has two main components SmartTokens and Connectors. "Through the use of smart-contracts, Smart Tokens can be created that hold one or more other tokens as connectors. Tokens may represent existing national currencies or other types of assets" [1].

=== Smart Tokens

"Smart Tokens™, are always available to be both bought and sold directly through their smart contracts. In other words, 4
the token’s governing software always offers to sell tokens to buyers and buy back tokens from sellers" [2].

"Each Smart Token has one or more connectors that link the Smart Token to other tokens in the network. These connectors hold a balance of another token, thus establishing a relationship between the Smart Token and the tokens held by its connectors, or its connected tokens" [2].

==== ERC20 compatibility

"All Smart Tokens are ERC20-compatible tokens, meaning they function as and are compatible with any system or service which supports these now-standard Ethereum-based tokens" [2]. There is an official https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md[Ethereum ERC20 standard interface for tokens] as well as many examples of ERC20 implementations in the field. For example, you can see the Solidity code for one of https://github.com/ConsenSys/Tokens/blob/master/contracts/eip20/EIP20.sol[Consensys’s ERC20 implementations here] and you can see the Solidity code for one of the https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol[OpenZeppelin StandardTokens here].

== Bancor implementation




= References

[1] https://github.com/bancorprotocol/contracts
[2] https://storage.googleapis.com/website-bancor/2018/04/01ba8253-bancor_protocol_whitepaper_en.pdf
[3] 


